# General settings
notifications:
  email: false
sudo: false

# Build matrix
os:
  - linux                       # This is currently Ubuntu 12.04 LTS
  # - osx
language: cpp

# Install, build, and test
addons:
  apt:
    sources:
      # - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      # - cmake
      - g++-5
      - gcc-5
      - gfortran-5
      - libhwloc-dev
      - libjemalloc-dev
      - libopenmpi-dev
      - openmpi-bin
install:
  - pushd "$HOME"
  - curl -O https://curl.haxx.se/ca/cacert.pem && export CURL_CA_BUNDLE="$(pwd)/cacert.pem"
  - git clone https://github.com/llnl/spack.git
  - cd spack
  - source share/spack/setup-env.sh
  - spack compilers
  - travis_wait spack install -j2 cereal
  - travis_wait spack install -j2 cmake
  # - travis_wait spack install -j2 hwloc
  # - travis_wait spack install -j2 openmpi
  - travis_wait spack install -j2 qthreads
  - spack find
  - spack view -d true hardlink "$HOME/spack-view" cereal
  - spack view -d true hardlink "$HOME/spack-view" cmake
  # - spack view -d true hardlink "$HOME/spack-view" hwloc
  # - spack view -d true hardlink "$HOME/spack-view" openmpi
  - spack view -d true hardlink "$HOME/spack-view" qthreads
  - export PATH="$HOME/spack-view/bin:$PATH"
  - popd
script:
  - echo "$PATH"
  - which cmake
  - cmake --version
  - $HOME/spack-view/bin/cmake --version
  - mkdir build && pushd build
  - cmake -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make -j2
  - make -j2 test
  - make -j2 install
  - popd
# after_success:
#   - make -j2 coverage
#   - codecov
#   - coveralls-lcov coverage.info
