# General settings
notifications:
  email: false
sudo: false
dist: trusty

# TODO:
# - build with Clang

# Build matrix
os:
  - linux
  # Building libraries via Spack takes too long for macOS and times out
  # - osx
language: cpp

# Install, build, and test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      # - gfortran-6
      # - libhwloc-dev
      # - libopenmpi-dev
      # - openmpi-bin
      - libmpich-dev
      - mpich
cache:
  directories:
    - $HOME/spack
before_cache:
  - rm -f "$HOME"/spack/travis_wait_*.log
install:
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      export CC=gcc-6
      export CXX=g++-6
      # export FC=gfortran-6
      export GCOV=gcov-6
      export comp=gcc@6
      export syscomp="$comp"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = osx ]; then
      brew update
      brew install gcc@5
      # brew install gfortran@5
      export CC=gcc-5
      export CXX=g++-5
      # export FC=gfortran-5
      export GCOV=gcov-5
      export comp=gcc@5
      export syscomp=clang
    fi
  - pushd "$HOME"
  - curl -O https://curl.haxx.se/ca/cacert.pem && export CURL_CA_BUNDLE="$(pwd)/cacert.pem"
  # The git repo might have been created from the cache
  - git clone https://github.com/llnl/spack.git || true
  - cd spack
  - git fetch origin && git reset --hard origin/develop
  - mkdir -p var/spack/repos/builtin/packages/funhpc && cp "$TRAVIS_BUILD_DIR"/package.py var/spack/repos/builtin/packages/funhpc/package.py
  - source share/spack/setup-env.sh
  - spack compilers
  # - travis_wait 60 spack install -j2 --only dependencies funhpc %"$comp" ^openmpi ^pkg-config %"$syscomp"
  - travis_wait 60 spack install -j2 --only dependencies funhpc %"$comp"
  - spack find
  - spack view -d true hardlink "$HOME/spack-view" cereal
  - spack view -d true hardlink "$HOME/spack-view" cmake
  - spack view -d true hardlink "$HOME/spack-view" googletest
  - spack view -d true hardlink "$HOME/spack-view" hwloc @:1.999.999
  - spack view -d true hardlink "$HOME/spack-view" jemalloc
  # - spack view -d true hardlink "$HOME/spack-view" openmpi
  - spack view -d true hardlink "$HOME/spack-view" qthreads
  - export PATH="$HOME/spack-view/bin:$PATH"
  - popd
script:
  - mkdir build && pushd build
  # - cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DGTEST_ROOT="$HOME/spack-view" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DGTEST_ROOT="$HOME/spack-view" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make -j2
  - make -j2 test CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 install
  - popd
after_success:
  - mkdir -p "$HOME/bin" && ln -s "$(which $GCOV)" "$HOME/bin/gcov" && ls -l "$HOME/bin" && export PATH="$HOME/bin:$PATH" && hash -r
  - mkdir build-coveralls && pushd build-coveralls
  - cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DGTEST_ROOT="$HOME/spack-view" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  - make -j2
  - make -j2 coveralls CTEST_OUTPUT_ON_FAILURE=1
  - popd
