# General settings
notifications:
  email: false
sudo: false

# TODO:
# - build with Clang
# - test coverage

# Build matrix
os:
  - linux                       # This is currently Ubuntu 12.04 LTS
  - osx
language: cpp

# Install, build, and test
addons:
  apt:
    sources:
      # - h-rayflood/llvm
      - ubuntu-toolchain-r-test
    packages:
      # - llvm-toolchain-3.6
      - g++-5
      - gcc-5
      - gfortran-5
cache:
  directories:
    - $HOME/spack
install:
  - if [ `uname` = Darwin ]; then brew update; brew install gcc@5; fi
  - pushd "$HOME"
  - curl -O https://curl.haxx.se/ca/cacert.pem && export CURL_CA_BUNDLE="$(pwd)/cacert.pem"
  # The git repo might have been created from the cache
  - git clone https://github.com/llnl/spack.git || true
  - cd spack
  - git pull
  - source share/spack/setup-env.sh
  - spack compilers
  - travis_wait 40 spack install -j2 cereal
  - travis_wait spack install -j2 cmake
  - travis_wait spack install -j2 hwloc
  - travis_wait spack install -j2 jemalloc
  - travis_wait 40 spack install -j2 openmpi
  - travis_wait spack install -j2 qthreads
  - spack find
  - spack view -d true hardlink "$HOME/spack-view" cereal
  - spack view -d true hardlink "$HOME/spack-view" cmake
  - spack view -d true hardlink "$HOME/spack-view" hwloc
  - spack view -d true hardlink "$HOME/spack-view" jemalloc
  - spack view -d true hardlink "$HOME/spack-view" openmpi
  - spack view -d true hardlink "$HOME/spack-view" qthreads
  - export PATH="$HOME/spack-view/bin:$PATH"
  - popd
script:
  - mkdir build && pushd build
  - cmake -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make -j2
  - make -j2 test CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 install
  - popd
after_success:
  - mkdir build-coveralls
  # - export COVERALLS_SERVICE_NAME=travis-ci
  # - export COVERALLS_REPO_TOKEN=abc12345
  - cmake -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  - make -j2
  - make -j2 coveralls CTEST_OUTPUT_ON_FAILURE=1
  - codecov
  - coveralls-lcov coverage.info
