# General settings
notifications:
  email: false
sudo: false

# TODO:
# - build with Clang
# - test coverage

# Build matrix
os:
  - linux                       # This is currently Ubuntu 12.04 LTS
  - osx
language: cpp

# Install, build, and test
addons:
  apt:
    sources:
      # - h-rayflood/llvm
      - ubuntu-toolchain-r-test
    packages:
      # - llvm-toolchain-3.6
      - g++-5
      - gcc-5
      - gfortran-5
cache:
  directories:
    - $HOME/spack
before_cache:
  - rm -f "$HOME"/spack/travis_wait_*.log
install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then
      export CC=gcc-5;
      export CXX=g++-5;
      export FC=gfortran-5;
      export GCOV=gcov-5;
    fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then
      brew update;
      brew install gcc@5;
      brew install gfortran@5;
      export CC=gcc-5;
      export CXX=g++-5;
      export FC=gfortran-5;
      export GCOV=gcov-5;
    fi
  - pushd "$HOME"
  - curl -O https://curl.haxx.se/ca/cacert.pem && export CURL_CA_BUNDLE="$(pwd)/cacert.pem"
  # The git repo might have been created from the cache
  # - git clone https://github.com/llnl/spack.git || true
  - rm -rf spack
  - git clone -b eschnett/cactusext https://github.com/eschnett/spack.git || true
  - cd spack
  - git pull
  - source share/spack/setup-env.sh
  - spack compilers
  - which $CC || true
  - which $CXX || true
  - which $FC || true
  - cat $HOME/.spack/*/compilers.yaml
  - travis_wait 40 spack install -j2 cereal
  - travis_wait spack install -j2 cmake
  - travis_wait spack install -j2 hwloc
  - travis_wait spack install -j2 jemalloc
  - travis_wait 60 spack install -j2 openmpi
  - travis_wait spack install -j2 qthreads
  - spack find
  - spack view -d true hardlink "$HOME/spack-view" cereal
  - spack view -d true hardlink "$HOME/spack-view" cmake
  - spack view -d true hardlink "$HOME/spack-view" hwloc
  - spack view -d true hardlink "$HOME/spack-view" jemalloc
  - spack view -d true hardlink "$HOME/spack-view" openmpi
  - spack view -d true hardlink "$HOME/spack-view" qthreads
  - export PATH="$HOME/spack-view/bin:$PATH"
  - popd
script:
  - mkdir build && pushd build
  - cmake -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make -j2
  - make -j2 test CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 install
  - popd
after_success:
  - which gcc || true
  - which g++ || true
  - which gcov || true
  - gcc --version || true
  - g++ --version || true
  - gcov --version || true
  - which $CC || true
  - which $CXX || true
  - which $GCOV || true
  - $CC --version || true
  - $CXX --version || true
  - $GCOV --version || true
  - mkdir -p "$HOME/bin" && ln -s "$(which $GCOV)" "$HOME/bin/gcov" && ls -l "$HOME/bin" && export PATH="$HOME/bin:$PATH" && hash -r
  - mkdir build-coveralls && pushd build-coveralls
  - cmake -DCMAKE_FIND_ROOT_PATH="$HOME/spack-view" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  - make -j2
  - make -j2 coveralls CTEST_OUTPUT_ON_FAILURE=1
  - popd
