# General settings
notifications:
  email: false
sudo: false

# Build matrix
os:
  - linux   # This is currently Ubuntu 12.04 LTS
  # - osx
language: cpp

# Install, build, and test
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5
before_install:
  - git clone https://github.com/llnl/spack.git
  - pushd spack
  - source share/spack/setup-env.sh
  - spack compilers
  - curl -O https://curl.haxx.se/ca/cacert.pem
  - export CURL_CA_BUNDLE="$(pwd)/cacert.pem"
  - spack install cereal
  - spack install cmake
  - spack install hwloc
  - spack install openmpi
  - spack install qthreads
  - spack view -d true hardlink $HOME cereal
  - spack view -d true hardlink $HOME cmake
  - spack view -d true hardlink $HOME hwloc
  - spack view -d true hardlink $HOME openmpi
  - spack view -d true hardlink $HOME qthreads
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_FIND_ROOT_PATH="$HOME" -DCMAKE_CXX_COMPILER="$HOME/bin/g++" -DCMAKE_INSTALL_PREFIX="$HOME" ..
  - make -j2
  - make -j2 test
  - make -j2 install
# after_success:
#   - make -j2 coverage
#   - codecov
#   - coveralls-lcov coverage.info
